### ISSUE TITLE
Exception has occurred: AttributeError module 'sieve' has no attribute 'Metadata'

### ISSUE THREAD

**Issue by pascal-maker** [sieve-community/fast-asd#1]
Trying to run the talknet main.py and keep getting the same error Exception has occurred: AttributeError
module 'sieve' has no attribute 'Metadata'
  File "/Users/pascal/fast-asd/talknet/main.py", line 4, in <module>
    metadata = sieve.Metadata(
               ^^^^^^^^^^^^^^
AttributeError: module 'sieve' has no attribute 'Metadata' Even tried from sieve import Metadata

**Comment by Andreaswt** [comment]
@pascal-maker Hey, you need to run "pip install sievedata", not pip install sieve

**Comment by pascal-maker** [comment]
Already did that same error still occurs.

**Comment by Andreaswt** [comment]
Did you uninstall the other package? sieve

**Comment by mvoodarla** [comment]
Hey! Apologies. You've confirmed the following doesn't work?

```
pip uninstall sieve
pip install sievedata --upgrade
```

If you'd like to just run this app as an API, you can do so with these [instructions](https://www.sievedata.com/functions/sieve/active_speaker_detection/guide) without needing to install anything in Python. However for that, you'd need a Sieve account.
